name: CI/CD Network

on:
  push:
    branches:  
       - master

    #paths:
    # - '.github/workflows/SQS-HML.yml'
    # - 'hml/sqs-fifo/**'  
#Start a project run os Ubuntu Machine  

jobs:

# Deploy stage
  
 Deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch 
      uses: actions/checkout@v3
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Terraform plan 
      run: |
        terraform init
        terraform validate
        terraform plan -out=plan.tfplan
    
    - if: github.ref == 'refs/heads/main'
      name: Terraform apply
      run: |
        terraform apply -auto-approve